/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chainlink from "./chainlink";
export type { chainlink };
export type { IPriceOracle } from "./IPriceOracle";
export type { PriceOracleConstants } from "./PriceOracleConstants";
