/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as beehiveinnovationfactory from "./beehiveinnovationfactory";
export type { beehiveinnovationfactory };
import type * as oracleprice from "./oracleprice";
export type { oracleprice };
export type { ERC20Gild } from "./ERC20Gild";
export type { ERC20GildFactory } from "./ERC20GildFactory";
export type { Gildable } from "./Gildable";
export type { NativeGild } from "./NativeGild";
export type { NativeGildFactory } from "./NativeGildFactory";
